'use strict';

let M='orders', R='Total', SELECTED=null;
let MODEL={}, TOTAL={}, SUMMARY={}, IVALID={};
const GREEN='#1f7a3f', GREY='#c9c7bd';
const fmtN=new Intl.NumberFormat('en-US',{maximumFractionDigits:0});
const fmtM=v=>(v<0?'-':'')+'$'+(Math.abs(v)>=1e6?(Math.abs(v)/1e6).toFixed(1)+'m':fmtN.format(Math.abs(v)));
const num=(v,m=M)=>m==='revenue'?fmtM(v):fmtN.format(v);
const signed=(v,m=M)=>(v>0?'+':'')+num(v,m);
const short=(v,m)=>{const a=Math.abs(v),p=v<0?'-':v>0?'+':'';const n=a>=1e6?(a/1e6).toFixed(1)+'m':a>=1e3?(a/1e3).toFixed(0)+'k':fmtN.format(a);return p+(m==='revenue'?'$':'')+n};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

Promise.all([
  fetch('model/generated/halo-created-orders.json').then(r=>r.json()),
  fetch('model/generated/halo-created-revenue.json').then(r=>r.json()),
  fetch('model/generated/halo-incrementality-orders.json').then(r=>r.json()),
  fetch('model/generated/halo-incrementality-revenue.json').then(r=>r.json()),
  fetch('model/generated/report-summary.json').then(r=>r.json()),
  fetch('model/generated/placebo-incrementality-orders.json').then(r=>r.json()),
  fetch('model/generated/placebo-incrementality-revenue.json').then(r=>r.json())
]).then(([createdOrders,createdRevenue,totalOrders,totalRevenue,summary,valOrders,valRevenue])=>{
  MODEL={orders:createdOrders,revenue:createdRevenue}; TOTAL={orders:totalOrders,revenue:totalRevenue};
  SUMMARY=summary; IVALID={orders:valOrders,revenue:valRevenue}; buildTabs(); bind(); render();
}).catch(err=>{document.getElementById('hero').textContent='The model files could not be loaded';document.getElementById('heroTxt').textContent=err.message});

function data(){return MODEL[M].views[R]||MODEL[M].views.Total}
function cell(s,d){return data().cells[s+'|'+d]||null}
function cellFor(m,g,s,d){return MODEL[m].views[g]?.cells[s+'|'+d]||null}
function totalCellFor(m,g,s){return TOTAL[m].views[g]?.cells[s+'|Total Business']||null}
function accepted(c){return !!(c?.passes_placebo&&c.effect>0&&c.lower80>0)}
function rowTotalFor(m,g,s){return MODEL[m].views[g]?.row_totals?.[s]??MODEL[m].destinations.reduce((a,d)=>a+(cellFor(m,g,s,d)?.effect||0),0)}
function rowTotal(s){return rowTotalFor(M,R,s)}
function direct(s){return cell(s,s)?.effect||0}
function routeCount(m,g,s){return MODEL[m].destinations.filter(d=>cellFor(m,g,s,d)?.passes_placebo).length}
function rowIntervalFor(m,g,s){const c=totalCellFor(m,g,s);return {total:c?.effect||0,low:c?.lower80||0,high:c?.upper80||0,se:c?.standard_error||0,passes:!!c?.passes_placebo,accepted:accepted(c),q:c?.placebo_q_value}}
function sourceStatus(s,g=R){
  const o=rowIntervalFor('orders',g,s),r=rowIntervalFor('revenue',g,s);
  if(o.accepted&&r.accepted)return {key:'protect',label:'Supported / test',action:'Protect while confirming with a holdout'};
  if(o.accepted||r.accepted)return {key:'partial',label:'Partial evidence',action:'Hold steady; test the unresolved outcome'};
  if((o.passes&&o.total<0)||(r.passes&&r.total<0))return {key:'test',label:'TEST counterintuitive',action:'Do not cut; investigate in a holdout'};
  if(o.passes||r.passes)return {key:'unresolved',label:'Unresolved total',action:'Hold steady; the total interval includes zero'};
  return {key:'none',label:'No incrementality evidence',action:'No budget claim; create better variation'};
}
function buildTabs(){const geos=['Total',...MODEL.orders.metadata.geographies];document.getElementById('rTabs').innerHTML=geos.map(g=>`<button data-r="${esc(g)}" class="${g==='Total'?'on':''}">${g==='United Kingdom'?'UK':g==='United States'?'US':esc(g)}</button>`).join('')}
function bind(){document.getElementById('mTabs').onclick=e=>{if(!e.target.dataset.m)return;M=e.target.dataset.m;SELECTED=null;setOn('mTabs','m',M);render()};document.getElementById('rTabs').onclick=e=>{if(!e.target.dataset.r)return;R=e.target.dataset.r;SELECTED=null;setOn('rTabs','r',R);render()}}
function setOn(id,k,v){document.querySelectorAll('#'+id+' button').forEach(b=>b.classList.toggle('on',b.dataset[k]===v))}
function render(){renderHero();renderMatrix();renderPanel();renderSpill();renderShift();renderText()}

function renderHero(){
  const supported=MODEL[M].channels.filter(s=>rowIntervalFor(M,R,s).accepted),routes=supported.reduce((a,s)=>a+routeCount(M,R,s),0),v=IVALID[M].summary;
  document.getElementById('hero').innerHTML=`${supported.length} / ${MODEL[M].channels.length} <em>source rows clear the final total-business gate</em>`;
  document.getElementById('heroTxt').innerHTML=`In <strong>${esc(R)}</strong>, the calculator supports total-business ${M} creation for <strong>${supported.length?supported.map(esc).join(', '):'none'}</strong>. Its ${routes} printed destination cells divide those supported totals; they are not separate claims that can be added again.`;
  document.getElementById('warn').innerHTML=`<strong>Raw association is not the answer.</strong> Fake histories reproduced ${Math.round(100*v.fake_to_observed_absolute_median)}% of the raw headline magnitude, so the calculator rejects that raw model. After calibration, the separate held-out gate published <strong>0 false source rows in both the median and worst of ${v.heldout_placebo_runs} fake histories</strong>. This is strong falsification performance, but only a randomized holdout can establish causality.`;
}

function renderMatrix(){
  const src=MODEL[M].channels,dst=MODEL[M].destinations,max=Math.max(...src.flatMap(s=>dst.map(d=>Math.abs(cell(s,d)?.effect||0))),1),rowMax=Math.max(...src.map(rowTotal),1);
  let h='<table class="m"><thead><tr><th></th>'+dst.map(d=>`<th class="col">${esc(d)}</th>`).join('')+'<th class="col" style="font-weight:800;color:#1a1a1a">Total business</th></tr></thead><tbody>';
  for(const s of src){h+=`<tr><th>${esc(s)}</th>`;for(const d of dst){const c=cell(s,d),v=c?.effect||0,ok=!!c?.passes_placebo,a=ok?.15+.75*Math.sqrt(v/max):0,bg=ok?`rgba(31,122,63,${a})`:'#e8e6df',fg=ok&&a>.52?'#fff':'#333',sel=SELECTED&&SELECTED[0]===s&&SELECTED[1]===d?' sel':'';h+=`<td><div class="cell${sel}" data-s="${esc(s)}" data-d="${esc(d)}" style="background:${bg};color:${fg}" title="${ok?`${signed(v)} incremental ${M} created by ${esc(s)} and credited to ${esc(d)}`:'No created result published: total incrementality, routing, or both are unresolved'}">${ok&&v>=1?signed(v):'—'}</div></td>`}const total=rowTotal(s),ok=accepted(totalCellFor(M,R,s)),a=ok?.18+.72*Math.sqrt(total/rowMax):0,bg=ok?`rgba(31,122,63,${a})`:'#e8e6df',fg=ok&&a>.52?'#fff':'#222';h+=`<td style="border-left:3px solid #1a1a1a"><div class="cell" style="background:${bg};color:${fg};font-weight:800;cursor:default" title="${ok?`${signed(total)} supported total-business ${M} created by ${esc(s)}`:'No supported total-business creation result'}">${ok?signed(total):'—'}</div></td></tr>`}h+='</tbody></table>';
  const el=document.getElementById('matrix');el.innerHTML=h;el.querySelectorAll('.cell[data-d]').forEach(x=>x.onclick=()=>{SELECTED=[x.dataset.s,x.dataset.d];renderMatrix();renderPanel()});document.getElementById('matcap').textContent=`Estimated incremental ${M} created by the row source and credited to the column over 365 days in ${R}. A cell prints only when total source incrementality and destination routing both pass. Printed cells sum exactly to Total business.`;
}

function renderPanel(){
  if(!SELECTED){document.getElementById('panel').innerHTML='<h3 style="color:#888;font-weight:500">Select a cell</h3><p style="color:#888">Pick a source and destination pair to see the total-business incrementality result and how the supported total was routed.</p>';return}
  const [s,d]=SELECTED,c=cell(s,d);if(!c)return;const tc=totalCellFor(M,R,s),ok=!!c.passes_placebo,totalOK=accepted(tc),pct=100*(c.routing_weight||0),verdict=ok?'Created result published':'No created result published',cls=ok?'v-hold':'v-no';
  const why=ok?`The model supports ${num(tc.effect)} total-business ${M} created by ${s}; ${pct.toFixed(1)}% is credited to ${d}.`:`The calculator does not claim that ${s} created ${M} credited to ${d}, because total incrementality, destination routing, or both did not clear the gate.`;
  document.getElementById('panel').innerHTML=`<h3>${esc(s)} &rarr; ${esc(d)}</h3><span class="verdict ${cls}">${verdict}</span><p class="why">${esc(why)}</p><div class="stats"><div class="stat"><div class="k">Created here</div><div class="v">${ok?signed(c.effect):'—'}</div><div class="ex">supported total × routing share</div></div><div class="stat"><div class="k">Share of supported total</div><div class="v">${ok?pct.toFixed(1)+'%':'—'}</div></div><div class="stat"><div class="k">Supported source total</div><div class="v">${totalOK?signed(tc.effect):'—'}</div><div class="ex">total-business decision layer</div></div><div class="stat"><div class="k">Total 80% interval</div><div class="v">${tc?signed(tc.lower80)+' to '+signed(tc.upper80):'—'}</div></div><div class="stat"><div class="k">Total FDR q-value</div><div class="v">${tc?.placebo_q_value!=null?(100*tc.placebo_q_value).toFixed(2)+'%':'—'}</div><div class="ex">99% source gate</div></div><div class="stat"><div class="k">Routing estimate</div><div class="v">${c.routing_effect?signed(c.routing_effect):'—'}</div><div class="ex">used only as a positive share</div></div><div class="stat"><div class="k">Routing gate</div><div class="v">${c.routing_passes?'Pass':'Unresolved'}</div></div><div class="stat"><div class="k">Row status</div><div class="v">${esc((c.row_status||'unresolved').replaceAll('_',' '))}</div></div></div>`;
}

function renderSpill(){
  const cut=Math.abs(SUMMARY.scenario_relative_change),rows=MODEL.orders.channels.map(s=>{const spend=SUMMARY.views[R]?.sources?.[s]?.spend,saved=spend==null?null:spend*cut,o=rowIntervalFor('orders',R,s),r=rowIntervalFor('revenue',R,s),status=sourceStatus(s);return{s,saved,o,r,status,oc:routeCount('orders',R,s),rc:routeCount('revenue',R,s)}}).sort((a,b)=>(b.r.accepted?b.r.total:0)-(a.r.accepted?a.r.total:0));
  let h='<div class="hscroll"><table class="s tight"><tr><th class="stick">Channel</th><th>20% spend<br>saved</th><th>Orders created<br><span class="asof">total 80%</span></th><th>Revenue created<br><span class="asof">total 80%</span></th><th>Revenue created<br>/ $ saved</th><th>Saved spend<br>/ order created</th><th>Evidence</th><th>Status</th><th>Action</th></tr>';
  for(const x of rows){const ratio=x.saved&&x.r.accepted?x.r.total/x.saved:null,cpo=x.saved&&x.o.accepted?x.saved/x.o.total:null;h+=`<tr><td class="l stick">${esc(x.s)}</td><td>${x.saved==null?'—':fmtM(x.saved)}</td><td>${x.o.accepted?`${short(x.o.total,'orders')}<div class="asof">${short(x.o.low,'orders')} to ${short(x.o.high,'orders')}</div>`:x.o.passes?'Unresolved':'—'}</td><td>${x.r.accepted?`${short(x.r.total,'revenue')}<div class="asof">${short(x.r.low,'revenue')} to ${short(x.r.high,'revenue')}</div>`:x.r.passes?'Unresolved':'—'}</td><td>${ratio==null?'—':ratio.toFixed(2)+'×'}</td><td>${cpo==null?'—':'$'+fmtN.format(cpo)}</td><td>O ${x.o.accepted?'pass':'—'} (${x.oc} routes) · R ${x.r.accepted?'pass':'—'} (${x.rc} routes)</td><td><strong class="${x.status.key==='test'?'val-bad':''}">${x.status.label}</strong></td><td class="wrap">${x.status.action}</td></tr>`}h+='</table></div><p class="cap">Economics appear only when the source-to-total-business result clears the final gate. Destination routing determines where that supported total is credited; it cannot manufacture a total.</p>';document.getElementById('spill').innerHTML=h;
}

function renderShift(){
  const el=document.getElementById('shift');if(!el)return;const cap=document.getElementById('shiftcap');if(cap)cap.innerHTML=(M==='revenue'?'Revenue':'Orders')+' created by source for <strong>'+esc(R)+'</strong>. Gray is the amount credited back to the source itself; green is the supported total across all destinations.';
  const rows=MODEL[M].channels.map(k=>({k,a:direct(k),b:rowTotal(k)})).sort((x,y)=>y.b-x.b),W=880,L=118,RPAD=88,rowH=30,top=6,HH=top+rows.length*rowH+24,hi=Math.max(1,...rows.flatMap(x=>[x.a,x.b])),plotW=W-L-RPAD,x=v=>L+v/hi*plotW;
  let svg=`<div class="key"><span><i style="background:${GREY}"></i>Credited to same channel</span><span><i style="background:${GREEN}"></i>Total created</span></div><svg viewBox="0 0 ${W} ${HH}" role="img" aria-label="Own credited created effect compared with total created effect by channel"><line class="axis" x1="${L}" x2="${L}" y1="0" y2="${HH-19}"/>`;
  rows.forEach((r,i)=>{const y=top+i*rowH,bar=(v,yy,color)=>`<rect x="${L}" y="${yy}" width="${Math.max(v?1:0,x(v)-L)}" height="8" rx="1" fill="${color}"/>`;svg+=`<text class="lab" x="${L-7}" y="${y+14}" text-anchor="end">${esc(r.k)}</text>${bar(r.a,y+3,GREY)}${bar(r.b,y+13,GREEN)}<text class="val" x="${x(r.b)+5}" y="${y+21}" text-anchor="start" fill="${GREEN}">${r.b?signed(r.b):'—'}</text>`});svg+='</svg>';el.innerHTML=svg;
}

function renderText(){
  const v=IVALID[M].summary,supported=MODEL[M].channels.filter(s=>rowIntervalFor(M,R,s).accepted),routes=supported.reduce((a,s)=>a+routeCount(M,R,s),0);
  document.getElementById('rely').innerHTML=`<div class="hscroll"><table class="s"><tr><th>Diagnostic</th><th>${esc(R)} ${M}</th></tr><tr><td class="l">Source rows tested</td><td>${MODEL[M].channels.length}</td></tr><tr><td class="l">Source rows clearing final gate</td><td>${supported.length}</td></tr><tr><td class="l">Published destination routes</td><td>${routes}</td></tr><tr><td class="l">Raw fake / observed magnitude</td><td>${(100*v.fake_to_observed_absolute_median).toFixed(1)}%</td></tr><tr><td class="l">Held-out fake rows, median</td><td>${v.heldout_fake_passing_rows_median}</td></tr><tr><td class="l">Held-out fake rows, worst</td><td>${v.heldout_fake_passing_rows_max}</td></tr><tr><td class="l">Held-out fake histories</td><td>${v.heldout_placebo_runs}</td></tr></table></div><p class="cap">The high raw fake share demonstrates confounding in the uncorrected model. The held-out rows evaluate the final decision rule on fake histories that were not used to set it.</p>`;
  document.getElementById('sens').innerHTML=`<p><strong>Layer one asks whether spend here predicts incremental total-business ${M}.</strong> It models each source against the sum of every credited destination, removes its empirical fake-history behavior, applies a 99% source gate, and requires a positive 80% interval. <strong>Layer two asks where the supported total is credited.</strong> Only positive destination routes that pass their own diagnostics receive a share.</p><div class="eq">created at destination = supported total-business incrementality × accepted routing share<br>sum of printed destinations = supported total-business incrementality</div>`;
  const geos=MODEL[M].metadata.geographies,stability=MODEL[M].channels.map(s=>{const total=rowIntervalFor(M,R,s),vals=geos.map(g=>rowIntervalFor(M,g,s)),pos=vals.filter(x=>x.accepted).length,unresolved=vals.filter(x=>x.passes&&!x.accepted).length,none=vals.filter(x=>!x.passes).length,o=rowIntervalFor('orders',R,s),r=rowIntervalFor('revenue',R,s),agree=o.accepted&&r.accepted?'Both pass':o.accepted||r.accepted?'One passes':'Neither passes';return{s,total,pos,unresolved,none,agree}}).sort((a,b)=>(b.total.accepted?b.total.total:0)-(a.total.accepted?a.total.total:0));
  document.getElementById('stab').innerHTML='<div class="hscroll"><table class="s"><tr><th class="stick">Source</th><th>Supported markets</th><th>Unresolved markets</th><th>No evidence</th><th>Orders / revenue</th><th>Total-business result</th></tr>'+stability.map(x=>`<tr><td class="l stick">${esc(x.s)}</td><td>${x.pos} / ${geos.length}</td><td>${x.unresolved} / ${geos.length}</td><td>${x.none} / ${geos.length}</td><td>${x.agree}</td><td>${x.total.accepted?signed(x.total.total):'—'}</td></tr>`).join('')+'</table></div>';
  document.getElementById('cons').innerHTML='<div class="method"><p><strong>All views use the same two-layer output.</strong> The Total business value comes from the source-level incrementality model. The matrix and gray/green bar chart divide that exact accepted total using destination routing weights. Unresolved sources publish no created destinations, so attribution movement can never be mistaken for orders created.</p></div>';
  const groups={protect:[],partial:[],unresolved:[],test:[],none:[]};MODEL.orders.channels.forEach(s=>groups[sourceStatus(s).key].push(s));
  document.getElementById('suggest').innerHTML=`<div class="callout"><h4>Supported on both outcomes</h4><p>${groups.protect.length?groups.protect.map(esc).join(', '):'None in this view.'} Protect while confirming with a randomized holdout.</p></div><div class="callout"><h4>Partial evidence</h4><p>${groups.partial.length?groups.partial.map(esc).join(', '):'None in this view.'} One outcome clears the gate and the other does not.</p></div><div class="callout"><h4>Unresolved</h4><p>${[...groups.unresolved,...groups.test].length?[...groups.unresolved,...groups.test].map(esc).join(', '):'None in this view.'} Do not infer a cut or an increase from these observational estimates.</p></div><div class="callout"><h4>No incrementality evidence</h4><p>${groups.none.length?groups.none.map(esc).join(', '):'None in this view.'} This means the calculator cannot make a claim, not that effectiveness is zero.</p></div>`;
  const rank={protect:3,partial:2,unresolved:1},paid=MODEL.orders.channels.filter(s=>SUMMARY.views[R]?.sources?.[s]?.spend!=null),priorities=paid.filter(s=>rank[sourceStatus(s).key]).sort((a,b)=>rank[sourceStatus(b).key]-rank[sourceStatus(a).key]).slice(0,3),days=56;
  let exp='<div class="hscroll"><table class="s tight"><tr><th class="stick">Priority</th><th>Test market</th><th>Holdout</th><th>Duration</th><th>Spend withheld</th><th>Primary KPI</th><th>Model-sized 8-week effect</th><th>Decision rule</th></tr>';
  for(const s of priorities){const matching=geos.filter(g=>rowIntervalFor('revenue',g,s).accepted||rowIntervalFor('orders',g,s).accepted),pool=matching.length?matching:geos,geo=[...pool].sort((a,b)=>(SUMMARY.views[b]?.sources?.[s]?.spend||0)-(SUMMARY.views[a]?.sources?.[s]?.spend||0))[0],geoSpend=SUMMARY.views[geo]?.sources?.[s]?.spend||0,saved=geoSpend*Math.abs(SUMMARY.scenario_relative_change),rev=rowIntervalFor('revenue',geo,s),orders=rowIntervalFor('orders',geo,s),revEff=rev.accepted?rev.total*days/365:0,ordEff=orders.accepted?orders.total*days/365:0;exp+=`<tr><td class="l stick">${esc(s)}</td><td>${esc(geo)} audience / geo clusters</td><td>20%</td><td>8 weeks</td><td>${fmtM(saved*days/365)}</td><td>Total new-customer revenue<br><span class="asof">secondary: total orders</span></td><td>${revEff?short(revEff,'revenue'):'revenue unresolved'}; ${ordEff?short(ordEff,'orders'):'orders unresolved'}</td><td class="wrap">Treat the channel as causal only if the randomized total-business interval excludes zero in the predicted direction.</td></tr>`}exp+='</table></div><p class="cap">Use pre-period experimental-unit variance to power the test before assignment. Observational model size is a planning input, not proof.</p>';document.getElementById('hold').innerHTML=exp;
  document.getElementById('appendix').innerHTML=`<p><strong>Status:</strong> ${esc(MODEL[M].status)}.</p><p><strong>Window:</strong> ${MODEL[M].metadata.date_min} through ${MODEL[M].metadata.date_max}; ${fmtN.format(MODEL[M].metadata.row_count)} geography-days.</p><p><strong>Measures:</strong> orders and net revenue are fitted independently against total business, then routed to destinations.</p><p><strong>Decision rule:</strong> empirical-null correction, 99% source gate, and positive 80% interval; the final rule is checked on ${v.heldout_placebo_runs} separately held-out fake histories.</p><p><strong>Important limitation:</strong> no completed randomized experiments were available for calibration, so this remains observational evidence rather than a causal estimate.</p>`;
}
